# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main2

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'c55d756b-faa7-47de-ae2d-835ad2e9dc15'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG-LogicApps'
    location: 'Australia Southeast'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/SushilWork/LogicAppConsumptionGit/main/LogicAppCnspn.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'